### ISSUE TITLE
--install-layout=deb not recognized

### ISSUE THREAD

**Issue by maxx-bachurin** [astraw/stdeb#175]
I am trying to debianize my python project and get the following error during the build:

```bash
python setup.py --command-packages=stdeb.command bdist_deb
...
python3 setup.py install --force --root=debian/python3-data-manager --no-compile -O0 --install-layout=deb --prefix=/usr
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --install-layout not recognized
```

I have the following packages installed:

```bash
pip3 list
Package    Version
---------- -------
pip        19.2.3
setuptools 50.3.2
stdeb      0.10.0
```

**Comment by pirate** [comment]
Also having this problem when trying to build with `stdeb` on github actions ubuntu runner.

It seems to be caused when the version of python running setuptools is not the system/apt installed version of python installed with the debian-specific patches applied (which are required for `--install-layout`).

Setting `SETUPTOOLS_USE_DISTUTILS=stdlib` or `SETUPTOOLS_USE_DISTUTILS=local` didn't help either.

This is our `.github/workflows/debian.yml`:
```yaml
name: Build Debian package

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64

      - name: Install packaging dependencies
        run: |
          sudo apt install -y python3 python3-dev python3-pip python3-venv python3-all dh-python debhelper devscripts dput software-properties-common python3-distutils python3-setuptools python3-wheel python3-stdeb
          pip3 install --upgrade pip setuptools wheel stdeb

      - name: Build Debian/Apt bdist_deb
        run: |
          python3 setup.py --command-packages=stdeb.command bdist_deb

      - name: Install archivebox from deb
        run: |
          apt install ./deb_dist/archivebox*.deb
```

This fails on `python3 setup.py --command-packages=stdeb.command bdist_deb` with `error: option --install-layout not recognized` despite it being on a debian-based system.
